/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.microfunctions.mfnapi;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-01-13")
public class TriggerInfoTimer implements org.apache.thrift.TBase<TriggerInfoTimer, TriggerInfoTimer._Fields>, java.io.Serializable, Cloneable, Comparable<TriggerInfoTimer> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TriggerInfoTimer");

  private static final org.apache.thrift.protocol.TField TIMER_INTERVAL_MILLISECONDS_FIELD_DESC = new org.apache.thrift.protocol.TField("timerIntervalMilliseconds", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TriggerInfoTimerStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TriggerInfoTimerTupleSchemeFactory();

  public long timerIntervalMilliseconds; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TIMER_INTERVAL_MILLISECONDS((short)1, "timerIntervalMilliseconds");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TIMER_INTERVAL_MILLISECONDS
          return TIMER_INTERVAL_MILLISECONDS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMERINTERVALMILLISECONDS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TIMER_INTERVAL_MILLISECONDS, new org.apache.thrift.meta_data.FieldMetaData("timerIntervalMilliseconds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TriggerInfoTimer.class, metaDataMap);
  }

  public TriggerInfoTimer() {
  }

  public TriggerInfoTimer(
    long timerIntervalMilliseconds)
  {
    this();
    this.timerIntervalMilliseconds = timerIntervalMilliseconds;
    setTimerIntervalMillisecondsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TriggerInfoTimer(TriggerInfoTimer other) {
    __isset_bitfield = other.__isset_bitfield;
    this.timerIntervalMilliseconds = other.timerIntervalMilliseconds;
  }

  public TriggerInfoTimer deepCopy() {
    return new TriggerInfoTimer(this);
  }

  @Override
  public void clear() {
    setTimerIntervalMillisecondsIsSet(false);
    this.timerIntervalMilliseconds = 0;
  }

  public long getTimerIntervalMilliseconds() {
    return this.timerIntervalMilliseconds;
  }

  public TriggerInfoTimer setTimerIntervalMilliseconds(long timerIntervalMilliseconds) {
    this.timerIntervalMilliseconds = timerIntervalMilliseconds;
    setTimerIntervalMillisecondsIsSet(true);
    return this;
  }

  public void unsetTimerIntervalMilliseconds() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TIMERINTERVALMILLISECONDS_ISSET_ID);
  }

  /** Returns true if field timerIntervalMilliseconds is set (has been assigned a value) and false otherwise */
  public boolean isSetTimerIntervalMilliseconds() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TIMERINTERVALMILLISECONDS_ISSET_ID);
  }

  public void setTimerIntervalMillisecondsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TIMERINTERVALMILLISECONDS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case TIMER_INTERVAL_MILLISECONDS:
      if (value == null) {
        unsetTimerIntervalMilliseconds();
      } else {
        setTimerIntervalMilliseconds((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case TIMER_INTERVAL_MILLISECONDS:
      return getTimerIntervalMilliseconds();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case TIMER_INTERVAL_MILLISECONDS:
      return isSetTimerIntervalMilliseconds();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TriggerInfoTimer)
      return this.equals((TriggerInfoTimer)that);
    return false;
  }

  public boolean equals(TriggerInfoTimer that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_timerIntervalMilliseconds = true;
    boolean that_present_timerIntervalMilliseconds = true;
    if (this_present_timerIntervalMilliseconds || that_present_timerIntervalMilliseconds) {
      if (!(this_present_timerIntervalMilliseconds && that_present_timerIntervalMilliseconds))
        return false;
      if (this.timerIntervalMilliseconds != that.timerIntervalMilliseconds)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(timerIntervalMilliseconds);

    return hashCode;
  }

  @Override
  public int compareTo(TriggerInfoTimer other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetTimerIntervalMilliseconds()).compareTo(other.isSetTimerIntervalMilliseconds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimerIntervalMilliseconds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timerIntervalMilliseconds, other.timerIntervalMilliseconds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TriggerInfoTimer(");
    boolean first = true;

    sb.append("timerIntervalMilliseconds:");
    sb.append(this.timerIntervalMilliseconds);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TriggerInfoTimerStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TriggerInfoTimerStandardScheme getScheme() {
      return new TriggerInfoTimerStandardScheme();
    }
  }

  private static class TriggerInfoTimerStandardScheme extends org.apache.thrift.scheme.StandardScheme<TriggerInfoTimer> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TriggerInfoTimer struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TIMER_INTERVAL_MILLISECONDS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timerIntervalMilliseconds = iprot.readI64();
              struct.setTimerIntervalMillisecondsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TriggerInfoTimer struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TIMER_INTERVAL_MILLISECONDS_FIELD_DESC);
      oprot.writeI64(struct.timerIntervalMilliseconds);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TriggerInfoTimerTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TriggerInfoTimerTupleScheme getScheme() {
      return new TriggerInfoTimerTupleScheme();
    }
  }

  private static class TriggerInfoTimerTupleScheme extends org.apache.thrift.scheme.TupleScheme<TriggerInfoTimer> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TriggerInfoTimer struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetTimerIntervalMilliseconds()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTimerIntervalMilliseconds()) {
        oprot.writeI64(struct.timerIntervalMilliseconds);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TriggerInfoTimer struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.timerIntervalMilliseconds = iprot.readI64();
        struct.setTimerIntervalMillisecondsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

