#   Copyright 2020 The KNIX Authors
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

FROM ubuntu:18.04 as builder

ENV DEBIAN_FRONTEND=noninteractive

ENV REDIS_VERSION=6.2.3

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      build-essential \
      cmake \
      make \
      wget \
      unzip \
      libssl1.0.0 \
      libssl1.0-dev \ 
      libasl-dev \
      libsasl2-dev \
      pkg-config \
      libsystemd-dev \
      zlib1g-dev \
      flex \
      bison \
      tar \
      mtools \
      git \
      ca-certificates \
      automake \
      autoconf \
      libncurses5-dev


RUN set -ex && \
    mkdir /build && \
    cd /build && \
    wget https://github.com/redis/redis/archive/refs/tags/${REDIS_VERSION}.tar.gz && \
    tar -xvf ${REDIS_VERSION}.tar.gz && \
    mv redis-${REDIS_VERSION} redis && \
    cd redis && \
    make

